In [78]:
import pandas as pd
import seaborn as sb
import numpy as np
from sklearn import ensemble, preprocessing, model_selection, metrics, decomposition, neighbors 
import os
from joblib import dump
pd.set_option('display.max_columns', 70)
pd.set_option('display.max_rows', 70)

In [2]:
currentFolder = os.getcwd()
allData = pd.read_csv(currentFolder + '/data/resultingData/merged_data.csv')
allData

Unnamed: 0  Unnamed: 0_x          District             Member  \
0             0             0         Alabama 1      Bradley Byrne   
1             1             1         Alabama 2        Martha Roby   
2             2             2         Alabama 3        Mike Rogers   
3             3             3         Alabama 4    Robert Aderholt   
4             4             4         Alabama 5          Mo Brooks   
..          ...           ...               ...                ...   
426         426           426       Wisconsin 5  Jim Sensenbrenner   
427         427           427       Wisconsin 6     Glenn Grothman   
428         428           428       Wisconsin 7        Tom Tiffany   
429         429           429       Wisconsin 8     Mike Gallagher   
430         430           430  Wyoming at-large         Liz Cheney   

          Party Prior experience Education  Assumed office        Residence  \
0    Republican              Yes        JD            2014         Fairhope   
1    Republican              Yes        JD            2011       Montgomery   
2    Republican              Yes        JD            2003             Saks   
3    Republican              Yes        JD            1997       Haleyville   
4    Republican              Yes        JD            2011       Huntsville   
..          ...              ...       ...             ...              ...   
426  Republican              Yes        JD            1979  Menomonee Falls   
427  Republican              Yes        JD            2015    Campbellsport   
428  Republican              Yes  Bachelor            2020         Minocqua   
429  Republican               No       PhD            2017        Green Bay   
430  Republican              Yes        JD            2017          Jackson   

     Born Spouse  Childrens  Years in office  Age when elected  Unnamed: 0_y  \
0    1955    Yes          4                6                59             0   
1    1976    Yes          2                9                35             1   
2    1958    Yes          0               17                45             2   
3    1965    Yes          0               23                32             3   
4    1954    Yes          4                9                57             4   
..    ...    ...        ...              ...               ...           ...   
426  1943     No          2               41                36           432   
427  1955     No          0                5                60           433   
428  1957    Yes          3                0                63           434   
429  1984     No          0                3                33           435   
430  1966    Yes          5                3                51           436   

     Total Population  Percentage Male  Percentage Female  Median age(years)  \
0              715346         0.481645           0.518355               40.3   
1              678122         0.481250           0.518750               38.8   
2              708409         0.488335           0.511665               39.2   
3              686297         0.490092           0.509908               40.5   
4              725634         0.494778           0.505222               39.5   
..                ...              ...                ...                ...   
426            731341         0.490269           0.509731               41.3   
427            714886         0.505683           0.494317               41.9   
428            710420         0.503212           0.496788               44.7   
429            735997         0.499363           0.500637               40.7   
430            577737         0.506492           0.493508               38.5   

     Race Total population  Fraction White  Fraction Black or A.American  \
0                   715346        0.670933                      0.275239   
1                   678122        0.629199                      0.321442   
2                   708409        0.693084                      0

In [3]:
data = allData.drop(columns = ['Unnamed: 0', 'Unnamed: 0_x', 'District', 'Member', 'Prior experience', 'Education', 
                               'Assumed office', 'Residence', 'Born', 'Spouse', 'Childrens', 'Years in office',
                               'Age when elected', 'Unnamed: 0_y', 'Race Total population','Birth Total Population', 'State'])
data

Party  Total Population  Percentage Male  Percentage Female  \
0    Republican            715346         0.481645           0.518355   
1    Republican            678122         0.481250           0.518750   
2    Republican            708409         0.488335           0.511665   
3    Republican            686297         0.490092           0.509908   
4    Republican            725634         0.494778           0.505222   
..          ...               ...              ...                ...   
426  Republican            731341         0.490269           0.509731   
427  Republican            714886         0.505683           0.494317   
428  Republican            710420         0.503212           0.496788   
429  Republican            735997         0.499363           0.500637   
430  Republican            577737         0.506492           0.493508   

     Median age(years)  Fraction White  Fraction Black or A.American  \
0                 40.3        0.670933                      0.275239   
1                 38.8        0.629199                      0.321442   
2                 39.2        0.693084                      0.259665   
3                 40.5        0.861266                      0.074561   
4                 39.5        0.744043                      0.180412   
..                 ...             ...                           ...   
426               41.3        0.902241                      0.029012   
427               41.9        0.923484                      0.021094   
428               44.7        0.929920                      0.007969   
429               40.7        0.899565                      0.016375   
430               38.5        0.914695                      0.006347   

     Fraction Indian or Alaskan Native  Fraction Asian  \
0                             0.009774        0.014856   
1                             0.004185        0.010974   
2                             0.001835        0.018420   
3                             0.006398        0.004476   
4                             0.004304        0.016834   
..                                 ...             ...   
426                           0.002839        0.034065   
427                           0.004823        0.023854   
428                           0.018889        0.017080   
429                           0.025837        0.021440   
430                           0.028014        0.010051   

     People: Race Native Hawaiian and Other Pacific Islander  Fraction Other  \
0                                             0.000256              0.010751   
1                                             0.000038              0.012030   
2                                             0.000000              0.008880   
3                                             0.000986              0.029633   
4                                             0.000220              0.027506   
..                                                 ...                   ...   
426                                           0.000216              0.012652   
427                                           0.000172              0.007716   
428                                           0.000757              0.005777   
429                                           0.000375              0.013363   
430                                           0.001923              0.015228   

     People: Hispanic or Latino and Race Total population  \
0                                               715346      
1                                               678122      
2                                               708409      
3                                               686297      
4                                               725634      
..                                                 ...      
426                                             731341      
427                                             714886      
428                                             710420      


In [4]:
features = data.columns.tolist()
for i in range(len(features)):
    print(type(data.loc[1,features[i]]))

<class 'str'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>


In [5]:
data['Party'] = data['Party'].replace({'Republican':0,'Democratic':1,'Libertarian':2})
target = data.pop('Party')
target

0      0
1      0
2      0
3      0
4      0
      ..
426    0
427    0
428    0
429    0
430    0
Name: Party, Length: 431, dtype: int64

In [6]:
data = pd.concat([data,pd.get_dummies(data['Most Employees'], prefix='employer')],axis=1)
data = pd.concat([data,pd.get_dummies(data['Largest Payroll'], prefix='paying')],axis=1)
data = pd.concat([data,pd.get_dummies(data['Most Establishments'], prefix='established')],axis=1)
data = data.drop(columns = ['Most Employees', 'Largest Payroll', 'Most Establishments'])

In [7]:
data

Total Population  Percentage Male  Percentage Female  Median age(years)  \
0              715346         0.481645           0.518355               40.3   
1              678122         0.481250           0.518750               38.8   
2              708409         0.488335           0.511665               39.2   
3              686297         0.490092           0.509908               40.5   
4              725634         0.494778           0.505222               39.5   
..                ...              ...                ...                ...   
426            731341         0.490269           0.509731               41.3   
427            714886         0.505683           0.494317               41.9   
428            710420         0.503212           0.496788               44.7   
429            735997         0.499363           0.500637               40.7   
430            577737         0.506492           0.493508               38.5   

     Fraction White  Fraction Black or A.American  \
0          0.670933                      0.275239   
1          0.629199                      0.321442   
2          0.693084                      0.259665   
3          0.861266                      0.074561   
4          0.744043                      0.180412   
..              ...                           ...   
426        0.902241                      0.029012   
427        0.923484                      0.021094   
428        0.929920                      0.007969   
429        0.899565                      0.016375   
430        0.914695                      0.006347   

     Fraction Indian or Alaskan Native  Fraction Asian  \
0                             0.009774        0.014856   
1                             0.004185        0.010974   
2                             0.001835        0.018420   
3                             0.006398        0.004476   
4                             0.004304        0.016834   
..                                 ...             ...   
426                           0.002839        0.034065   
427                           0.004823        0.023854   
428                           0.018889        0.017080   
429                           0.025837        0.021440   
430                           0.028014        0.010051   

     People: Race Native Hawaiian and Other Pacific Islander  Fraction Other  \
0                                             0.000256              0.010751   
1                                             0.000038              0.012030   
2                                             0.000000              0.008880   
3                                             0.000986              0.029633   
4                                             0.000220              0.027506   
..                                                 ...                   ...   
426                                           0.000216              0.012652   
427                                           0.000172              0.007716   
428                                           0.000757              0.005777   
429                                           0.000375              0.013363   
430                                           0.001923              0.015228   

     People: Hispanic or Latino and Race Total population  \
0                                               715346      
1                                               678122      
2                                               708409      
3                                               686297      
4                                               725634      
..                                                 ...      
426                                             731341      
427                                             714886      
428                                             710420      
429                                             735997      
430                                             577737      

     Fraction Hi

In [8]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(data, target, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)

(344, 59)
(87, 59)


Before normalizing the data we would remove any outliers however in this case the outliers aren't faulty data and hence we'll keep them since they do display some statisticall data.

In [9]:
x_train.loc[:,'Total Population':'Total Occupation'] = x_train.loc[:,'Total Population':'Total Occupation'].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
x_test.loc[:,'Total Population':'Total Occupation'] = x_test.loc[:,'Total Population':'Total Occupation'].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

C:\Users\Asus\Anaconda3\envs\MachineLearning\lib\site-packages\pandas\core\indexing.py:964: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [10]:
model = ensemble.RandomForestClassifier(max_depth = 12)#Create model
print("Fitting data to random forest.")
model.fit(x_train, y_train) #Train model

Fitting data to random forest.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=12, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [11]:
scores = model_selection.cross_val_score(model, x_train, y_train, cv=10) #Do cross validation
print("\n Cross validation score: \n")
print(scores) #Report scores of cross validation
print("\n Mean cv score: ", np.mean(scores))


 Cross validation score: 

[0.85714286 0.88571429 0.8        0.82857143 0.88235294 0.82352941
 0.91176471 0.70588235 0.76470588 0.85294118]

 Mean cv score:  0.8312605042016805


In [12]:
prediction = model.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

0.735632183908046

 Confussion matrix:
 [[27 21  0]
 [ 1 37  0]
 [ 1  0  0]]


So the results from just applying a random forest classifier results in an accuracy of 72.4% on the test set. The next thing we'll do is look at how to improve the performance. 

First we'll look at decreasing the dimensionality of the data by using principal component analysis which basically tries to project the data into a subspace of lower dimensions while keeping as much of the variance as possible.

In [60]:
pca = decomposition.PCA(0.95) #n_components hardcodes the dimension, setting the argument to a = (0,1) makes the algorithm calculate 
                              # n components explaining a*100% of the variance.
pca.fit(x_train)
x_train_low_dim = pca.transform(x_train)
x_test_low_dim = pca.transform(x_test)

In [61]:
print(pca.components_.shape)
print(pca.explained_variance_)


(22, 59)
[0.55233075 0.48326002 0.20815619 0.19319474 0.1532979  0.13113442
 0.10735963 0.09194254 0.07970079 0.07626534 0.0726826  0.05899485
 0.05145115 0.04085627 0.03493466 0.03364933 0.02768019 0.0228063
 0.02143812 0.01825248 0.01700646 0.01484478]


So we can reduce our data from the original 59 dimensions into 22 dimensions while still explaining 95% of the variance.

Now we'll train and test a new model using this lowere dimensional data.

In [82]:
model = ensemble.RandomForestClassifier(max_depth = 12)#Create model
print("Fitting data to random forest.")
model.fit(x_train, y_train) #Train model

scores = model_selection.cross_val_score(model, x_train, y_train, cv=10) #Do cross validation
print("\n Cross validation score: \n")
print(scores) #Report scores of cross validation
print("\n Mean cv score: ", np.mean(scores))

prediction = model.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

Fitting data to random forest.

 Cross validation score: 

[0.8        0.94285714 0.8        0.85714286 0.91176471 0.79411765
 0.88235294 0.73529412 0.73529412 0.85294118]

 Mean cv score:  0.8311764705882352
0.735632183908046

 Confussion matrix:
 [[26 22  0]
 [ 0 38  0]
 [ 1  0  0]]


Performing the PCA lowered the accuracy when using the same structure for the random forest classifier so now we'll try and find a better model by optimising the hyperparameters.

In [83]:
n_estimators = [int(x) for x in np.linspace(start = 1, stop = 1000, num = 100)]
max_features = ['auto', 'sqrt', 'log2']
max_depth = [int(x) for x in np.linspace(1, 110, num = 11)]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]

randomSearchGrid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [84]:
model = ensemble.RandomForestClassifier()
modelRandom = model_selection.RandomizedSearchCV(estimator = model, param_distributions = randomSearchGrid,
                               n_iter = 100, cv = 10, verbose=2, random_state=42, n_jobs = -1)
modelRandom.fit(x_train, y_train)
modelRandom.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   11.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  7.5min finished


{'n_estimators': 586,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'auto',
 'max_depth': 33,
 'bootstrap': False}

In [86]:
bestRandom = modelRandom.best_estimator_
prediction = bestRandom.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

0.735632183908046

 Confussion matrix:
 [[27 21  0]
 [ 1 37  0]
 [ 1  0  0]]


So after the random search we didn't improved the accuracy. Next up is doing a local grid search around the rprevious found parameters

In [87]:
searchGrid = {
    'bootstrap': [False],
    'max_depth': [40, 45, 50, 55, 60, 65],
    'max_features': ['sqrt'],
    'min_samples_leaf': [1, 2, 3],
    'min_samples_split': [1, 2, 3, 4],
    'n_estimators': [290, 300, 313, 320, 330]
}
model = ensemble.RandomForestClassifier()
modelGrid = model_selection.GridSearchCV(estimator = model, param_grid = searchGrid, 
                          cv = 10, n_jobs = -1, verbose = 2)
modelGrid.fit(x_train_low_dim, y_train)
modelGrid.best_params_

Fitting 10 folds for each of 360 candidates, totalling 3600 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    4.4s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   29.4s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done 997 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-1)]: Done 1442 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 1969 tasks      | elapsed:  7.2min
[Parallel(n_jobs=-1)]: Done 2576 tasks      | elapsed:  9.2min
[Parallel(n_jobs=-1)]: Done 3265 tasks      | elapsed: 11.7min
[Parallel(n_jobs=-1)]: Done 3600 out of 3600 | elapsed: 13.1min finished


{'bootstrap': False,
 'max_depth': 55,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 3,
 'n_estimators': 320}

In [88]:
bestGrid = modelGrid.best_estimator_
prediction = bestGrid.predict(x_test_low_dim)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

0.7126436781609196

 Confussion matrix:
 [[25 23  0]
 [ 1 37  0]
 [ 1  0  0]]


So here we saw a small improvement compared to the untuned parameters. Naturally we could continue this redifenment as much as we want.

In [76]:
searchGrid = {
    'bootstrap': [False],
    'max_depth': [58, 59, 60, 61, 62],
    'max_features': ['sqrt'],
    'min_samples_leaf': [1, 2],
    'min_samples_split': [3, 4, 5, 6],
    'n_estimators': [ 310, 313, 315]
}

model = ensemble.RandomForestClassifier()
modelGrid = model_selection.GridSearchCV(estimator = model, param_grid = searchGrid, 
                          cv = 10, n_jobs = -1, verbose = 2)
modelGrid.fit(x_train_low_dim, y_train)
print(modelGrid.best_params_)

bestGrid = modelGrid.best_estimator_
prediction = bestGrid.predict(x_test_low_dim)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

Fitting 10 folds for each of 120 candidates, totalling 1200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    4.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   24.6s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 997 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-1)]: Done 1200 out of 1200 | elapsed:  4.6min finished


{'bootstrap': False, 'max_depth': 59, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 6, 'n_estimators': 315}
0.6781609195402298

 Confussion matrix:
 [[22 26  0]
 [ 1 37  0]
 [ 1  0  0]]


In this notebook we used a built in function to perform random search and then grid search but ofcourse we could do it systematically changing a parameter at a time and plot how the accuracy is affected, though it should be noted that we'll then tune the parameters to work well with each others with the hope that it willl produce an atleast local optimal classifier.

Finally we'll compare our tuned random forest classifier with a tuned k-nearest neighbour classifier.

In [81]:
grid = {'n_neighbors': [int(x) for x in np.linspace(start = 1, stop = 20, num = 20)],
        'weights':['uniform', 'distance'],
        'algorithm': ['auto'],
        'p':[int(x) for x in np.linspace(start = 1, stop = 5, num = 5)]
        }
model = neighbors.KNeighborsClassifier()
modelGrid = model_selection.GridSearchCV(estimator = model, param_grid = grid, 
                          cv = 10, n_jobs = -1, verbose = 2)

modelGrid.fit(x_train_low_dim, y_train)
print(modelGrid.best_params_)

bestGrid = modelGrid.best_estimator_
prediction = bestGrid.predict(x_test_low_dim)
accuracy = metrics.accuracy_score(y_test,prediction)
print(accuracy)
print("\n Confussion matrix:\n %s" % metrics.confusion_matrix(y_test, prediction))

Fitting 10 folds for each of 200 candidates, totalling 2000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.6s
[Parallel(n_jobs=-1)]: Done 1586 tasks      | elapsed:    5.9s


{'algorithm': 'auto', 'n_neighbors': 4, 'p': 2, 'weights': 'distance'}
0.7241379310344828

 Confussion matrix:
 [[29 19  0]
 [ 4 34  0]
 [ 1  0  0]]


[Parallel(n_jobs=-1)]: Done 2000 out of 2000 | elapsed:    6.8s finished


This then shows that trying to predict how a district congres district will vote is fairly difficult using the data chosen in this project. Including the state might increase the accuracy however then we run the risk of learning what each state is voting for i.e. Alabama votes for republicans no matter the actual census data which is not what we want to do.